### PR TITLE
Fixes #1511: Double the size of the Avatar

### LINKED ISSUE #1511: Avatars are blurry on retina displays
Avatars are blurry on retina displays:

CleanShot 2021-05-17 at 17 10 56@2x

### PR DESCRIPTION
**Pull request by adaex**
ref #1511 

# Description

I tried to solve the problem that the avatar of the retina screen is very blurred, but I don't think I did well. 

I am not particularly familiar with vscode plugin development. I don't know how to judge whether the current screen is a retinal screen, at the same time, it is not sure whether directly doubling the size of the avatar will cause other problems. 

If I bring trouble to you, please forgive me. I really hope someone can help.

# Checklist

- [x] I have followed the guidelines in the Contributing document
- [x] My changes follow the coding style of this project
- [x] My changes build without any errors or warnings
- [x] My changes have been formatted and linted
- [x] My changes include any required corresponding changes to the documentation
- [x] My changes have been rebased and squashed to the minimal number (typically 1) of relevant commits
- [x] My changes have a descriptive commit message with a short title, including a `Fixes $XXX -` or `Closes #XXX -` prefix to auto-close the issue that your PR addresses

### CODE REVIEW

**Review by eamodio — CHANGES_REQUESTED** [review]
Excellent approach, but we should move your fix here.

Add `size *= 2;` to before line `77` below
https://github.com/Axosoft/vscode-gitlens/blob/36de8cf5451b609c3596570540f60c645b0dc943/src/avatars.ts#L75-L77

**Comment by adaex** [comment]
@eamodio  Updated. PTAL

**Review by eamodio — APPROVED** [review]
Looks great!

**Comment by eamodio** [comment]
Thank you so much for your contribution!

Thank you!

**Pull request merged**
